model:
  chunk_size_factor: 10
  hidden_size: 1150
  nlayers: 3
  batch_size: 32
  input_size: 400
  train_batch_size: 80
  eval_batch_size: 10
  test_batch_size: 1
  seq_len: 80
  epochs: 100000
  lr: 1e-3
corpus_loc: 'CS6316-Final-Project/data/penn/'